<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\StrmManager.Common.Domain\StrmManager.Common.Domain.csproj" />
    <ProjectReference Include="..\..\Catalog\StrmManager.Modules.Catalog.Domain\StrmManager.Modules.Catalog.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
