// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrmManager.Modules.Catalog.Infrastructure.Database;

#nullable disable

namespace StrmManager.Modules.Catalog.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Episodes.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Runtime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc");

                    b.HasIndex("ReleaseAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("SeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Runtime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc");

                    b.HasIndex("ReleaseAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique();

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Series.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.SourceAttempts.SourceAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DifferencePercentage")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("ExpectedDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("source_attempts", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.StrmFiles.StrmFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId")
                        .IsUnique();

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("strm_files", (string)null);
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Movies.Movie", b =>
                {
                    b.OwnsOne("StrmManager.Modules.Catalog.Domain.Shared.ExternalIds", "ExternalIds", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("imdb_id");

                            b1.Property<string>("TmdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("tmdb_id");

                            b1.Property<string>("TvdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("tvdb_id");

                            b1.HasKey("MovieId");

                            b1.HasIndex("ImdbId")
                                .IsUnique();

                            b1.ToTable("movies");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.Navigation("ExternalIds")
                        .IsRequired();
                });

            modelBuilder.Entity("StrmManager.Modules.Catalog.Domain.Series.Series", b =>
                {
                    b.OwnsOne("StrmManager.Modules.Catalog.Domain.Shared.ExternalIds", "ExternalIds", b1 =>
                        {
                            b1.Property<Guid>("SeriesId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("imdb_id");

                            b1.Property<string>("TmdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("tmdb_id");

                            b1.Property<string>("TvdbId")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("tvdb_id");

                            b1.HasKey("SeriesId");

                            b1.HasIndex("ImdbId")
                                .IsUnique();

                            b1.ToTable("series");

                            b1.WithOwner()
                                .HasForeignKey("SeriesId");
                        });

                    b.Navigation("ExternalIds")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
