<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StrmManager.Modules.Catalog.Application\StrmManager.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\StrmManager.Common.Presentation\StrmManager.Common.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
